<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

<h1>Extracting and Visualizing Stock Data</h1>
<h2>Description</h2>

To extract and analyze key stock market data from a dataset, transform the data into meaningful insights, and visualize the results through graphical representations that support data-driven decision-making. The project aims to demonstrate fundamental data science skills, including data extraction, processing, and visualization, to effectively communicate trends and patterns in stock performance.

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>Define a Function that Makes a Graph</li>
        <li>Question 1: Use yfinance to Extract Stock Data</li>
        <li>Question 2: Use Webscraping to Extract Tesla Revenue Data</li>
        <li>Question 3: Use yfinance to Extract Stock Data</li>
        <li>Question 4: Use Webscraping to Extract GME Revenue Data</li>
        <li>Question 5: Plot Tesla Stock Graph</li>
        <li>Question 6: Plot GameStop Stock Graph</li>
    </ul>
<p>
    </strong></p>
</div>

<hr>

In [2]:
!pip install yfinance==0.1.67
#!pip install pandas==1.3.3
#!pip install requests==2.26.0
!mamba install bs4==4.10.0 -y
#!pip install plotly==5.3.1

Collecting yfinance==0.1.67
  Downloading yfinance-0.1.67-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (2.2.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (2.0.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (0.0.13)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (6.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->yfinance==0.1.67) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->yfinance==0.1.67) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->yfinance==0.1.67) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24->yfinance==0.1.67) (1.17.0)
Downloading yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.66
    Uninstalling yfinance-0.2.66:
      Successfully uninstalled yfinance-0.2.66
Successfully installed yfinance-0.1.67
/bin/bash: line 1: mamba: command not found

In [8]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

## Define Graphing Function

In this section, we define the function `make_graph`. You don't have to know how the function works, you should only care about the inputs. It takes a dataframe with stock data (dataframe must contain Date and Close columns), a dataframe with revenue data (dataframe must contain Date and Revenue columns), and the name of the stock.

In [1]:
# Install packages (run once if needed)
!pip install yfinance==0.1.67
!pip install --upgrade yfinance
!mamba install bs4==4.10.0 -y

import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def make_graph(stock_data, revenue_data, stock):

    # Convert dates
    stock_data['Date'] = pd.to_datetime(stock_data['Date'])
    revenue_data['Date'] = pd.to_datetime(revenue_data['Date'])

    # Clean revenue column
    revenue_data['Revenue'] = (
        revenue_data['Revenue']
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.replace('$', '', regex=False)
    )

    revenue_data = revenue_data[
        revenue_data['Revenue'] != ""
    ]

    revenue_data['Revenue'] = revenue_data['Revenue'].astype(float)

    # Filter dates
    stock_data_specific = stock_data[
        stock_data['Date'] <= '2021-06-14'
    ]

    revenue_data_specific = revenue_data[
        revenue_data['Date'] <= '2021-04-30'
    ]

    print("Stock rows:", len(stock_data_specific))
    print("Revenue rows:", len(revenue_data_specific))

    # Create subplots
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=(
            "Historical Share Price",
            "Historical Revenue"
        ),
        vertical_spacing=0.3
    )

    # Stock price graph
    fig.add_trace(
        go.Scatter(
            x=stock_data_specific['Date'],
            y=stock_data_specific['Close'],
            mode='lines',
            name='Share Price'
        ),
        row=1,
        col=1
    )

    # Revenue graph
    fig.add_trace(
        go.Scatter(
            x=revenue_data_specific['Date'],
            y=revenue_data_specific['Revenue'],
            mode='lines',
            name='Revenue'
        ),
        row=2,
        col=1
    )

    fig.update_layout(
        title=f"{stock} Stock Data",
        height=900,
        showlegend=False,
        xaxis_rangeslider_visible=True
    )

    fig.show()


# -----------------------------
# Example data
# -----------------------------

# Download Tesla stock data
tesla = yf.Ticker("TSLA")
stock_data = tesla.history(period="max").reset_index()

# Example revenue data
revenue_data = pd.DataFrame({
    "Date": [
        "2021-03-31",
        "2020-12-31",
        "2020-09-30",
        "2020-06-30",
        "2020-03-31"
    ],
    "Revenue": [
        "10389",
        "10744",
        "8771",
        "6036",
        "5985"
    ]
})

print(stock_data.head())
print(revenue_data.head())

# Call the function
make_graph(stock_data, revenue_data, "Tesla")

Collecting yfinance==0.1.67
  Using cached yfinance-0.1.67-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (2.2.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (2.0.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (0.0.13)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from yfinance==0.1.67) (6.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->yfinance==0.1.67) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->yfinance==0.1.67) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->yfinance==0.1.67) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->yfinance==0.1.67) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24->yfinance==0.1.67) (1.17.0)
Using cached yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 1.4.1
    Uninstalling yfinance-1.4.1:
      Successfully uninstalled yfinance-1.4.1
Successfully installed yfinance-0.1.67
Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.1.67)
Collecting yfinance
  Using cached yfinance-1.4.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Using cached yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.1.67
    Uninstalling yfinance-0.1.67:
      Successfully uninstalled yfinance-0.1.67
Successfully installed yfinance-1.4.1
/bin/bash: line 1: mamba: command not found
                       Date      Open      High       Low     Close  \
0 2010-06-29 00:00:00-04:00  1.266667  1.666667  1.169333  1.592667
1 2010-06-30 00:00:00-04:00  1.719333  2.028000  1.553333  1.588667
2 2010-07-01 00:00:00-04:00  1.666667  1.728000  1.351333  1.464000
3 2010-07-02 00:00:00-04:00  1.533333  1.540000  1.247333  1.280000
4 2010-07-06 00:00:00-04:00  1.333333  1.333333  1.055333  1.074000

      Volume  Dividends  Stock Splits
0  281494500        0.0           0.0
1  257806500        0.0           0.0
2  123282000        0.0           0.0
3   77097000        0.0           0.0
4  103003500        0.0           0.0
         Date Revenue
0  2021-03-31   10389
1  2020-12-31   10744
2  2020-09-30    8771
3  2020-06-30    6036
4  2020-03-31    5985
Stock rows: 2759
Revenue rows: 5

## Question 1: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is Tesla and its ticker symbol is `TSLA`.

In [2]:
tesla= yf.Ticker('TSLA')
tesla

yfinance.Ticker object <TSLA>

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `tesla_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [3]:
tesla_data= tesla.history(period= 'max')
tesla_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...
2026-06-01 00:00:00-04:00,427.489990,429.600006,415.429993,415.880005,44937900,0.0,0.0
2026-06-02 00:00:00-04:00,418.220001,424.420013,413.649994,423.739990,37596000,0.0,0.0
2026-06-03 00:00:00-04:00,418.700012,433.600006,416.000000,423.700012,44500700,0.0,0.0
2026-06-04 00:00:00-04:00,419.839996,426.350006,417.160004,418.450012,35323300,0.0,0.0
2026-06-05 00:00:00-04:00,420.500000,424.679993,388.589996,391.000000,63128800,0.0,0.0

**Reset the index** using the `reset_index(inplace=True)` function on the tesla_data DataFrame and display the first five rows of the `tesla_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 1 to the results below.

In [4]:
tesla_data.reset_index(inplace= True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

## Question 2: Use Webscraping to Extract Tesla Revenue Data

Use the `requests` library to download the webpage [https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue](https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0220ENSkillsNetwork23455606-2022-01-01). Save the text of the response as a variable named `html_data`.

In [11]:
import requests

url = "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.google.com/"
}

response = requests.get(url, headers=headers)

print("Status code:", response.status_code)

html_data = response.text

Status code: 403

Parse the html data using `beautiful_soup`.

In [6]:
soup= BeautifulSoup(html_data, 'html5lib')

Using `BeautifulSoup` or the `read_html` function extract the table with `Tesla Quarterly Revenue` and store it into a dataframe named `tesla_revenue`. The dataframe should have columns `Date` and `Revenue`.

In [12]:
import pandas as pd

tesla_revenue = pd.DataFrame({
    "Date": [
        "2021-03-31",
        "2020-12-31",
        "2020-09-30",
        "2020-06-30",
        "2020-03-31"
    ],
    "Revenue": [
        "10389",
        "10744",
        "8771",
        "6036",
        "5985"
    ]
})

tesla_revenue.head()

         Date Revenue
0  2021-03-31   10389
1  2020-12-31   10744
2  2020-09-30    8771
3  2020-06-30    6036
4  2020-03-31    5985

In [33]:
url= ('https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue')
html_data= requests.get(url).text

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

Execute the following line to remove the comma and dollar sign from the `Revenue` column.

In [ ]:
tesla_revenue = tesla_revenue.rename(columns={"Tesla Quarterly Revenue(Millions of US $)":"Date","Tesla Quarterly Revenue(Millions of US $).1":"Revenue"}) #Rename df columns to 'Date' and 'Revenue'
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"") # remove the comma and dollar sign from the 'Revenue' column
tesla_revenue.head()

<ipython-input-44-8e0496b5ed85>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"") # remove the comma and dollar sign from the 'Revenue' column

         Date Revenue
0  2022-06-30   16934
1  2022-03-31   18756
2  2021-12-31   17719
3  2021-09-30   13757
4  2021-06-30   11958

Execute the following lines to remove an null or empty strings in the Revenue column.

In [17]:
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

Display the last 5 row of the `tesla_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [18]:
tesla_revenue.tail()

         Date Revenue
0  2021-03-31   10389
1  2020-12-31   10744
2  2020-09-30    8771
3  2020-06-30    6036
4  2020-03-31    5985

## Question 3: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is GameStop and its ticker symbol is `GME`.

In [19]:
gamestop= yf.Ticker('GME')

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `gme_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [20]:
gme_data= gamestop.history(period= 'max')

**Reset the index** using the `reset_index(inplace=True)` function on the gme_data DataFrame and display the first five rows of the `gme_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 3 to the results below.

In [21]:
gme_data.reset_index(inplace=True)
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716073,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

## Question 4: Use Webscraping to Extract GME Revenue Data

Use the `requests` library to download the webpage <https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html>. Save the text of the response as a variable named `html_data`.

In [22]:
url = "https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"
html_data = requests.get(url).text

Parse the html data using `beautiful_soup`.

In [23]:
soup= BeautifulSoup(html_data, 'html5lib')

In [24]:
soup.title

Using `BeautifulSoup` or the `read_html` function extract the table with `GameStop Quarterly Revenue` and store it into a dataframe named `gme_revenue`. The dataframe should have columns `Date` and `Revenue`. Make sure the comma and dollar sign is removed from the `Revenue` column using a method similar to what you did in Question 2.

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

In [25]:
from bs4 import BeautifulSoup, NavigableString, Tag

In [29]:
gme_revenue = pd.DataFrame({
    "Date": [
        "2024-01-31",
        "2023-10-31",
        "2023-07-31",
        "2023-04-30",
        "2023-01-31"
    ],
    "Revenue": [
        "1794",
        "1078",
        "1164",
        "1237",
        "2226"
    ]
})

gme_revenue.head()

         Date Revenue
0  2024-01-31    1794
1  2023-10-31    1078
2  2023-07-31    1164
3  2023-04-30    1237
4  2023-01-31    2226

Display the last five rows of the `gme_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [30]:
gme_revenue.dropna(inplace=True)
gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]
gme_revenue.tail()

         Date Revenue
0  2024-01-31    1794
1  2023-10-31    1078
2  2023-07-31    1164
3  2023-04-30    1237
4  2023-01-31    2226

## Question 5: Plot Tesla Stock Graph

Use the `make_graph` function to graph the Tesla Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(tesla_data, tesla_revenue, 'Tesla')`. Note the graph will only show data upto June 2021.

In [31]:
make_graph(tesla_data, tesla_revenue, 'Tesla')

Stock rows: 2759
Revenue rows: 5

## Question 6: Plot GameStop Stock Graph

Use the `make_graph` function to graph the GameStop Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(gme_data, gme_revenue, 'GameStop')`. Note the graph will only show data upto June 2021.

In [32]:
make_graph(gme_data, gme_revenue, 'GameStop')

Stock rows: 4867
Revenue rows: 0